const productData = {
    products: [
      {
        _id: "1",
        name: "Watch Nero",
        category: "Wrist Watch",
        Image: "../../../public/images/product-1.jpg",
        price: 150,
        brand: "ABC",
        rating: 4.5,
        numReviews: 20,
        description: "Powerful watch for the century",
      },
      {
        _id: "2",
        name: "New Silver watch",
        category: "Wrist Watch",
        Image: "../../public/images/product-2.jpg",
        price: 140,
        brand: "CDG",
        rating: 4.5,
        numReviews: 10,
        description: "This is an awesome watch",
      },
      {
        _id: "3",
        name: "Nokia phone",
        category: "Mobile Phone",
        Image: "../../public/images/product-3.jpg",
        price: 140,
        brand: "MMG",
        rating: 4,
        numReviews: 20,
        description: "Grreat phone to have",
      },
      {
        _id: "4",
        name: "Ladies shoe",
        category: "Shoe",
        Image: "../../public/images/product-4.jpg",
        brand: "HHE",
        price: 100,
        rating: 4.5,
        numReviews: 20,
        description: "Ladies favourite",
      },
      {
        _id: "5",
        name: "Canvas",
        category: "Casuals",
        Image: "../../public/images/product-5.jpg",
        brand: "WST",
        price: 150,
        rating: 4.5,
        numReviews: 20,
        description: "Powerful watch for the century",
      },
      {
        _id: "6",
        name: "Jean",
        category: "Trousers",
        Image: "../../public/images/product-6.jpg",
        brand: "GDD",
        price: 150,
        rating: 4.5,
        numReviews: 20,
        description: "Powerful watch for the century",
      },
    ],
  };
  


  export default productData;